export const default_state = {
	settings: {
		fontFamily: "",
		fontVariant: "",
		text: "@akashraj9828",
		size: 100,
		unionCheckbox: false,
		separateCheckbox: true,
		bezierAccuracy: "",
		delay: 0.1,
		duration: "",
		strokeWidth: 2,
		fillColor: "#f16f6b",
		strokeColor: "#ffffff",
		timingFunction: "linear",
		repeat: true,
	},
	output: {
		svg: "",
		css: "",
		js: "",
		pathLength: 0,
		charCount: 0,
		width: 0,
		height: 0,
	},
	meta: {
		initialized: false,
	},
};
